VamosONG/VamosApp

front/package-lock.json, front/package.json, front/src/App.jsx, front/src/main.jsx, front/src/views/Forms/Login/Login.jsx
Add Chakra Provider en el main.jsx / Creando Formularios de registro y login
=> addChakraProvider

Back/src/Routes/index.js
Se crearon rutas para con crud completo para: Trip, User, Driver,  Airport, Zone y Admin .
=> Se crearon rutas en routes/index.js

Back/src/Routes/index.js
Se crearon handlers para cada modelo y se agruparon en carpetas. 
Se modificaron nombres de rutas en Routes/index.js.
=> Branch modificando estructura

Back/src/Models/airports.js, Back/src/Models/zone.js, Back/src/dataBase.js, Back/src/server.js
Corregi errores de la db y el server.
=> ServerDB fixed bug

Back/src/Controllers/ZonesControllers/deleteZone.js, Back/src/Controllers/ZonesControllers/postZone.js, Back/src/Controllers/ZonesControllers/updateZone.js
=> Completado controller de Zones

Back/src/Controllers/driversControllers/postDrivers.js, Back/src/Handlers/DriverHandlers/getDriversHandler.js, Back/src/Handlers/DriverHandlers/postDriverHandler.js, Back/src/Models/admin.js, Back/src/Models/airports.js, Back/src/Models/driver.js, Back/src/Models/reviews.js, Back/src/Models/trip.js, Back/src/Models/usuario.js, Back/src/Models/zone.js, Back/src/dataBase.js
Hice algunas mejoras en los modelos y cree un control
=> Controller & Models

Back/src/Controllers/AdminControllers/deleteAdminController.js
Implementacion de deleteAdminController.
=> Se implemento el controlador deleteAdmin

Back/src/Controllers/ZonesControllers/postZone.js, Back/src/Controllers/ZonesControllers/updateZone.js
Correcciones en controller de zone
=> Branch correccion zone

front/src/App.jsx, front/src/components/navBar/NavBar.jsx, front/src/components/solicitudes/solicitudesDeViajes.jsx, front/src/redux/actions/index.js, front/src/redux/reducer/index.js, front/src/views/Forms/Login/Login.jsx, front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx
Para empezar con el flujo. Falta muchísimo
=> flujo de solicitud de viaje 1

Back/src/Controllers/driversControllers/deleteDriver.js, Back/src/Controllers/driversControllers/getDrivers.js, Back/src/Controllers/driversControllers/postDrivers.js, Back/src/Controllers/driversControllers/updateDrivers.js, Back/src/Controllers/utilsControllers/doReserve.js, Back/src/Controllers/utilsControllers/setDriver.js, Back/src/Handlers/DriverHandlers/getDriversHandler.js, Back/src/Handlers/DriverHandlers/postDriverHandler.js, Back/src/Handlers/utilsHandlers/doReserveHandler.js, Back/src/Handlers/utilsHandlers/setDriverHandler.js
Se probaron los handlers y controllers de Driver con thunder, corrigiendo errores.
=> Pruebas de Driver

Back/src/Controllers/tripsControllers/getTrips.js, Back/src/Controllers/tripsControllers/postTrip.js, Back/src/Handlers/TripHandlers/deleteTripHandler.js, Back/src/Handlers/TripHandlers/getTripsHandler.js, Back/src/Handlers/TripHandlers/postTripHandler.js, Back/src/Handlers/TripHandlers/updateTripHandler.js, Back/src/Models/trip.js, Back/src/Routes/index.js
probados los controllers y handler de trip. agregado :id a las rutas put y delete
=> controllersTripsProbados

Back/src/Controllers/usersControllers/getUsers.js, Back/src/Handlers/UserHandlers/getUsersHandler.js, Back/src/dataBase.js
Arregle un error del getUser que me habia quedado pendiente
=> Getuser error

Back/src/Controllers/ZonesControllers/deleteZone.js, Back/src/Controllers/ZonesControllers/getZones.js, Back/src/Controllers/ZonesControllers/postZone.js, Back/src/Controllers/ZonesControllers/updateZone.js, Back/src/Handlers/ZonesHandlers/deleteZoneHandler.js
Falta delete, recibe el id de params como undefined
=> Pruebas de zones

Back/index.js, Back/src/Controllers/tripsControllers/updateTrip.js, Back/src/Controllers/utilsControllers/doReserve.js, Back/src/Controllers/utilsControllers/setDriver.js, Back/src/Handlers/TripHandlers/deleteTripHandler.js, Back/src/Models/trip.js, Back/src/Routes/index.js
=> probandoServer

Back/index.js, Back/src/Controllers/AirportsControllers/getAirports.js, Back/src/Controllers/AirportsControllers/postAirport.js, Back/src/Controllers/AirportsControllers/updateAirports.js, Back/src/Handlers/AirportsHandlers/deleteAirportHandler.js, Back/src/Handlers/AirportsHandlers/getAirportsHandler.js, Back/src/Handlers/AirportsHandlers/postAirportHandler.js, Back/src/Handlers/AirportsHandlers/updateAirportHandler.js, Back/src/dataBase.js
cambie tambien el reinicio forzado de la base de datos a false para que no se borre todo
=> airports checkeados

Back/src/Controllers/reviewsControllers/getReviews.js, Back/src/Controllers/reviewsControllers/postReview.js, Back/src/Handlers/ReviewsHandlers/deleteReviewHandler.js, Back/src/Handlers/ReviewsHandlers/postReviewHandler.js, Back/src/Models/driver.js, Back/src/Models/reviews.js, Back/src/Models/user.js
Toque los models para que se relacionen correctamente las reseñas que hace un user a un driver.
=> Correcciones en postReview, getReviews y models Driver, User y Review

Back/src/Controllers/tripsControllers/postTrip.js, Back/src/Models/trip.js
Hice la relacion trips user/drivers
=> relacionTrips

Back/src/Controllers/tripsControllers/updateTrip.js, Back/src/Handlers/TripHandlers/updateTripHandler.js
Correccion de updateTrip, para que genere relaciones en caso de agregar un nuevo driver
=> Correccion updateTrip

Back/src/Controllers/filtersControllers/filtersController.js
Filter devuelve un objeto de tipo trip para pruebas
=> Branch filter test

front/src/components/solicitudes/solicitudesDeViajes.jsx, front/src/redux/actions/index.js, front/src/redux/reducer/index.js, front/src/views/detailChofer/DetailChofer.jsx
Conexion de front y back para mostrar las reservas y simular elegir un conductor
=> conexio back para mostrar todas las reservas

Back/index.js
cambios en archivos de drivers incluido modelo para adaptarlo a formulario de front.
=> adaptandoPostDriverAForm

Back/src/Controllers/driversControllers/postDrivers.js, Back/src/Handlers/DriverHandlers/postDriverHandler.js, Back/src/Models/driver.js
no se habian hecho los cambios. Ahora sí.
=> cambiosNoSehabianHecho

Back/src/Controllers/filtersControllers/filtersController.js, Back/src/Handlers/filtersHandlers/filtersHandler.js, Back/src/Handlers/filtersHandlers/getFilteredDriversHandler.js
Se agregaron precios segun origen, destino y cantidad de pasajeros. Varian si la fecha es feriado.
=> Branch prices

Back/src/Handlers/ReviewsHandlers/getReviewsHandler.js, Back/src/Models/trip.js
Se agrego busqueda por id de chofer a getReviews
=> Branch funciones extra

front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx
Se corrigio error ortografico y se limito el ingreso de fecha desde hoy en adelante (no permite fechas pasadas)
=> Correcciones simples de form de reserva

back/src/controllers/airportsControllers/deleteAirports.js, back/src/controllers/pricesControllers/deletePrice.js, back/src/controllers/pricesControllers/getPrices.js, back/src/controllers/pricesControllers/postPrice.js, back/src/controllers/pricesControllers/updatePrice.js, back/src/controllers/tripsControllers/updateTrip.js, back/src/controllers/zonesControllers/deleteZone.js, back/src/dataBase.js, back/src/handlers/airportsHandlers/deleteAirportHandler.js, back/src/handlers/pricesHandlers/deletePriceHandler.js, back/src/handlers/pricesHandlers/getPriceHandler.js, back/src/handlers/pricesHandlers/postPriceHandler.js, back/src/handlers/pricesHandlers/updatePriceHandler.js, back/src/handlers/zonesHandlers/deleteZoneHandler.js, back/src/models/price.js, back/src/routes/index.js
Se creo tabla Price en BD, que almacena los valores de viajes segun areopuerto-zona y cantidad de pax.
Se corrigieron metodos de Airport.
=> Tabla prices

back/src/controllers/reviewsControllers/postReview.js, back/src/handlers/tripHandlers/getTripsByIdHandler.js, back/src/routes/index.js
Se se aplico que el validador ahora sea en el estado "pending" en lugar de "reserved" para eso se vinculo a la funcion que creo ezequiel para tal efecto.
Se modificó el getTripsById Handler para enviar el id por body en lugar de params.
=> postReveiews4

back/.env, back/src/utils/mailing/mailing.js, back/src/utils/mailing/sendMailHandler.js
Se corrigieron problemas de exposicion de claves - Se genero un primer template HTML para mail de bienvenida.
=> Correccion de problemas de seguridad en mailing - Primer template de bienvenida

back/src/utils/mailing/mailing.js, back/src/utils/mailing/sendMailHandler.js
Mailing funcional (con mi email) para: Bienvenida, Reserva, Asignación de chofer, Modificaciones e info para chofer
=> Funcionando mailing

back/src/controllers/driversControllers/postDrivers.js, back/src/handlers/driverHandlers/setInactiveDriverHandler.js, back/src/models/driver.js, back/src/routes/index.js
Se corrigieron errores en routes.
Se agrego la prop INACTIVE al model Driver, se agrego el metodo setInactiveDriver y se corrigio postDriver.
=> Correccion routes y borrado logico driver

front/src/App.jsx, front/src/components/userProfile/userProfile.jsx, front/src/views/carouselVamos/carouselVamos.jsx, front/src/views/home/homeCompone/home.jsx, front/src/views/publiVamos/publiVamos.jsx
Se corrigieron errores en el home, se volvio responsi algunos apartados, y se creo la ruta del usuario, falta agregar para que le aparesca las reservas que realice el usuario y agregar para que pueda cambiar sus datos.
=> Cambios, Correccion de errores y apartado usuario

back/src/handlers/driverHandlers/getActiveDriversHandler.js, back/src/handlers/userHandlers/deleteUserHandler.js
Se hizo metodo getActiveDrivers para que solo muestre los activos (borrado logico)
=> metodo getActiveDrivers

back/src/controllers/mercadoPagoController/paymentController.js, front/package-lock.json, front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx, front/src/views/payments/paymentStatus.jsx
saque la funcion duplicada q rompia el codigo
=> arreglos mercadopago

front/src/components/about/About.jsx
Se realizaron cambios en el About para que tenga una mejor presentacion
=> Cambios About

front/src/redux/actions/index.js, front/src/redux/reducer/index.js, front/src/views/payments/paymentStatus.jsx
Quedó funcionando la boleta payment success y renderizada con la información.
=> mercadoPagoFUNCIONANDO

back/src/controllers/usersControllers/postUser.js, back/src/utils/mailing/sendMailHandler.js, front/src/redux/actions/index.js, front/src/views/Forms/ChoferFormulario/UpdateChoferForm.jsx, front/src/views/Forms/Registro/Registro.jsx
Ruben, toque las actions para agregar las peticiones, revisalo antes de aceptar
=> Vinculando mailing

back/package-lock.json, front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx
=> Mercado Pago

front/src/App.jsx, front/src/components/navBar/NavBar.jsx, front/src/views/questions/questions.jsx
Agregado el apartado de preguntas frecuentes y about
=> Cambios Visuales

back/src/controllers/mercadoPagoController/paymentController.js, front/src/App.jsx, front/src/redux/actions/index.js, front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx, front/src/views/payments/paymentStatus.jsx
Cambia el estado del trip de offer a reserved al pagar en mercado pago
=> mercadopagoDB

front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx
cambie el estilo del apartado de solicitudes de viaje, sigo trabajando en el logout que no quiere aparecer en la pagina >:C
=> Cambio de estilo formulario solicitud de viaje

back/src/controllers/filtersControllers/getReserves.js, back/src/handlers/filtersHandlers/getReservesHandler.js, back/src/handlers/filtersHandlers/searchDriversHandler.js, back/src/routes/index.js
El metodo recibe por body: 
{
"order": "A - Z", (si no ordena al reves)
"searchInput": "tum" (busca coincidencias en nombre, apellido, email, carType, carModel y airports donde trabaja)
} 
si no se envia alguno de estos parametros, no se aplica, si no se envia ninguno retorna todos los drivers
=> Filtro por searchBar y ordenamiento Alfabetico por nombre

front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx
se guardan los datos en el local storage, se quedan puestos en el formulario algunos pero algunos no.
=> localStorage1

back/src/controllers/adminControllers/getAdminEmails.js, back/src/controllers/tripsControllers/postTrip.js, back/src/controllers/usersControllers/postUser.js, back/src/handlers/userHandlers/postUserHandler.js, back/src/handlers/utilsHandlers/doReserveHandler.js, back/src/handlers/utilsHandlers/setDriverHandler.js, back/src/utils/mailing/mailing.js, back/src/utils/mailing/sendMailHandler.js, front/src/views/Forms/Registro/Registro.jsx
Registro: a user,
Reserva: a user y todos los admins,
Asignacion de chofer: a user y chofer.
=> Mailing a back

front/src/App.jsx, front/src/components/navBar/NavBar.jsx, front/src/redux/actions/index.js, front/src/views/Forms/LogOut/logout.jsx, front/src/views/Forms/Login/Login.jsx
PORQUE CREARON 3 BOTONES DE LOGOUT?
=> Cambios en el LogOut

front/src/views/Forms/SolicitudViaje/SolicitudViajeForm.jsx
ahora si se quedan los datos del local storage en todo el formulario. falta ajustar que se pueda hacer post sin tener que volver a seleccionarlos nomás, y que muestre placeholder cuando esté vacío. Proxima subida soluciono eso.
=> localStorage2.0ElRegresoDelJedi

front/src/App.jsx, front/src/components/solicitudes/solicitudesDeViajes.jsx, front/src/components/userProfile/adminProfile.jsx, front/src/views/Forms/ChoferFormulario/ChoferForm.jsx, front/src/views/Forms/ChoferFormulario/UpdateChoferForm.jsx, front/src/views/Forms/Login/Login.jsx, front/src/views/adminProfile/reviewAdmin.jsx, front/src/views/adminProfile/userViewAdmin.jsx, front/src/views/driversViewAdmin/driverTable.jsx, front/src/views/driversViewAdmin/filtersData/orderFilter.jsx, front/src/views/driversViewAdmin/filtersData/reviewFilter.jsx, front/src/views/driversViewAdmin/filtersData/userFilter.jsx
Se realizo cambios en los estilos de los formularios y la vista de administrador, hay que agregar mas apartados.
=> Cambios en los formularios

back/src/controllers/usersControllers/getUserById.js, front/package-lock.json, front/src/components/userProfile/updateUserDataForms.jsx, front/src/components/userProfile/userProfile.jsx, front/src/views/Forms/Login/Login.jsx, front/src/views/adminProfile/userViewAdmin.jsx
Perfil de usuario responsive, listo.
=> User view profile

front/src/App.jsx, front/src/components/solicitudes/solicitudesDeViajes.jsx, front/src/components/userProfile/adminProfile.jsx, front/src/views/stadistic/Stadistics/stadistic.jsx
Se agrego el boton de estadisticas al panel de admin
=> estadisticas

front/src/components/userProfile/adminProfile.jsx, front/src/views/adminProfile/userViewAdmin.jsx
Hice unos arreglos ya que se rompio todo con el push de han
=> cambiosadmin

front/src/components/userProfile/adminProfile.jsx, front/src/views/stadistic/Stadistics/stadistic.jsx
Cambie el Idioma de los botones de Admin asi no estan mesclados, acepten asi mati no se enoje
=> Cambios de Idioma

back/src/controllers/reviewsControllers/getReviewById.js, front/src/components/solicitudes/solicitudesDeViajesPending.jsx, front/src/components/solicitudes/solicitudesDeViajesReserved.jsx
solo cambios menores y el getReviewsById.
=> getReviewById

front/src/assets/home.jsx, front/src/views/home/homeCompone/home.jsx
=> Tumbes y talara

front/src/App.jsx, front/src/utils/ProtectedRoute.jsx, front/src/views/Forms/LogOut/logout.jsx
Esto es el pull para que se recargue en la misma pagina
=> no se recarga la pagina

front/src/redux/actions/index.js, front/src/redux/reducer/index.js, front/src/views/driversViewAdmin/filtersData/orderFilter.jsx
funcionando el filtrado por input en drivers. algunas cosas por arreglar.
=> filtradoDriversBack1

back/src/handlers/filtersHandlers/getFilteredDriversHandler.js
recibe:
{
"searchInput":" ", 
"airports":" ", 
"quantityPassengers":  ,  (entero)
"date": "aaaa-mm-dd"
}
=> Filtro de drivers mejorado

front/src/components/editPrices/editPrice.jsx, front/src/components/editPrices/editPricesComponent.jsx, front/src/components/solicitudes/solicitudesDeViajesCompleted.jsx, front/src/components/solicitudes/solicitudesDeViajesPending.jsx, front/src/components/solicitudes/solicitudesDeViajesReserved.jsx, front/src/views/Forms/ChoferFormulario/ChoferForm.jsx, front/src/views/adminProfile/userViewAdmin.jsx, front/src/views/driversViewAdmin/driverTable.jsx
Cambios en los tamaños de las tablas, falta que alguien agregue el paginado y los filtros funcionen
=> Cambios en las tablas

front/src/views/driversViewAdmin/driverTable.jsx, front/src/views/driversViewAdmin/filtersData/orderFilter.jsx
Listos filtros combinados de drivers con search bar.
=> filtrosDriversConSearcher

front/src/views/adminProfile/userViewAdmin.jsx, front/src/views/driversViewAdmin/driverTable.jsx
Se agrego un paginado a usuarios y a drivers
=> Paginado users/drivers

front/package-lock.json, front/package.json, front/src/App.css, front/src/App.jsx, front/src/views/Forms/Login/LoginViajes.jsx, front/src/views/payments/paymentStatus.jsx
=> Transiciones y otros cambios

front/src/components/userProfile/userProfile.jsx
Se modifico el perfil de usuario
=> Perfil user

front/src/components/ReviewAndReseña/reviewAndReseña.jsx, front/src/components/cardUserTrips/cardUserTrips.jsx, front/src/components/userProfile/userProfile.jsx, front/src/views/driversViewAdmin/DetailDriver/ViewBtnDetailDriver.jsx, front/src/views/driversViewAdmin/DetailDriver/driverDetail.jsx, front/src/views/driversViewAdmin/DetailDriver/driverDetailMobile.jsx, front/src/views/driversViewAdmin/driverTable.jsx
rediseño de reseñar viaje, responsive
=> ViewMessage
